### ISSUE TITLE
Reset time

### ISSUE THREAD

**Issue by ankkk** [Lexxus/jq-timeTo#17]
Hi, tell me how to reset the timer after time is over?

**Comment by X-factor89** [comment]
Hello, I think you can try call timer again in callback function. Somethink like this:
	function showMyTimer(groupSeconds)
	{
		$('#timer').timeTo({
			seconds: groupSeconds,
			countdownAlertLimit: 10,
			callback: trigerTimeOut
		});
	}
	
	showMyTimer(30);
		
	function trigerTimeOut()
	{
		showMyTimer(30);
	}

**Comment by Lexxus** [comment]
Hi,

I've already fixed the reset method, so you can reset the timer in this way:

$('#timer').timeTo('reset');

However, there are another issues therefor I didn't release new version yet.
