### ISSUE TITLE
Count down faster when selector contains multiple elements

### ISSUE THREAD

**Issue by hsfzxjy** [Lexxus/jq-timeTo#18]
Just try:

```
<div class="clock"></div>
<div class="clock"></div>
....
<script>
    $('.clock').timeTo();
</script>
```

Interestingly, you will find that the clock counts down twice a second.

**Comment by drrest** [comment]
Not only twice...
If you have (for example) 5 elements with different names (so counter for all elements will skip 5 seconds per each second)
Please fix this bug...

**Comment by hsfzxjy** [comment]
Er, anybody alive?

**Comment by Lexxus** [comment]
Already fixed.
