### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by attora** [Lexxus/jq-timeTo#25]
Hi,

If I refresh page after countdown finish, the countdown restart with 99:23:59:59. 
how can we stop that to 00:00:00:00?
thanks

**Comment by trainspotting** [comment]
I was just coming to report the same issue..... If anyone visits a page after a countdown (which was originally set with a future date) has reached zero, then it seems to have started again counting down to some unknown and unwanted time!

Did you ever get a response or solution to this?

**Comment by Lexxus** [comment]
Hi!

Thank you for the explanation. I will try to solve this issue.

**Comment by trainspotting** [comment]
Hi Lexxus. Great! Thanks for being able to take a look at this... Hope you are able to figure out why it's doing this and find a fix!

**Comment by Lexxus** [comment]
Fixed.

**Comment by trainspotting** [comment]
Great. When do you plan to do the next update to the download file (or is that a silly question... perhaps I don't know where to look?!)

**Comment by Lexxus** [comment]
Now it is possible to install by NPM: npm install time-to
Also it is still available in GitHub as general and as minified js-files.

**Comment by trainspotting** [comment]
Does the 'DOWNLOAD ZIP' button on GitHub automatically package up all the latest files? I've just download that and using those I still see the same issue with an expired countdown continuing to countdown to 'something' after page load.

**Comment by Lexxus** [comment]
Could you somehow show me that issue? Or show me the script that creates
this broken countdown?

**Comment by trainspotting** [comment]
Sure... I'll send you a link to where you can see it... I'll send it to the email you have showing on your account here.

**Comment by trainspotting** [comment]
Great. Didn't realise I was still on an older version... working great now! Thanks...
